package com.github.diamond.web.model;

import java.util.Date;

public class ConfProjectConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.CONFIG_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.CONFIG_KEY
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.CONFIG_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.CONFIG_DESC
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String configDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PROJECT_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.MODULE_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.OPT_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String optUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.OPT_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRODUCTION_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String productionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRODUCTION_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String productionUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRODUCTION_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date productionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.TEST_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String testValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.TEST_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String testUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.TEST_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date testTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRE_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String preValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRE_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String preUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_config.PRE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date preTime;

    private String orderField;

    public String getOrderField() {
        return orderField;
    }

    public void setOrderField(String orderField) {
        this.orderField = orderField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.CONFIG_ID
     *
     * @return the value of conf_project_config.CONFIG_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.CONFIG_ID
     *
     * @param configId the value for conf_project_config.CONFIG_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.CONFIG_KEY
     *
     * @return the value of conf_project_config.CONFIG_KEY
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.CONFIG_KEY
     *
     * @param configKey the value for conf_project_config.CONFIG_KEY
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.CONFIG_VALUE
     *
     * @return the value of conf_project_config.CONFIG_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.CONFIG_VALUE
     *
     * @param configValue the value for conf_project_config.CONFIG_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.CONFIG_DESC
     *
     * @return the value of conf_project_config.CONFIG_DESC
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getConfigDesc() {
        return configDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.CONFIG_DESC
     *
     * @param configDesc the value for conf_project_config.CONFIG_DESC
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setConfigDesc(String configDesc) {
        this.configDesc = configDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PROJECT_ID
     *
     * @return the value of conf_project_config.PROJECT_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PROJECT_ID
     *
     * @param projectId the value for conf_project_config.PROJECT_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.MODULE_ID
     *
     * @return the value of conf_project_config.MODULE_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.MODULE_ID
     *
     * @param moduleId the value for conf_project_config.MODULE_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.DELETE_FLAG
     *
     * @return the value of conf_project_config.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.DELETE_FLAG
     *
     * @param deleteFlag the value for conf_project_config.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.OPT_USER
     *
     * @return the value of conf_project_config.OPT_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getOptUser() {
        return optUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.OPT_USER
     *
     * @param optUser the value for conf_project_config.OPT_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setOptUser(String optUser) {
        this.optUser = optUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.OPT_TIME
     *
     * @return the value of conf_project_config.OPT_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.OPT_TIME
     *
     * @param optTime the value for conf_project_config.OPT_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRODUCTION_VALUE
     *
     * @return the value of conf_project_config.PRODUCTION_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getProductionValue() {
        return productionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRODUCTION_VALUE
     *
     * @param productionValue the value for conf_project_config.PRODUCTION_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProductionValue(String productionValue) {
        this.productionValue = productionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRODUCTION_USER
     *
     * @return the value of conf_project_config.PRODUCTION_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getProductionUser() {
        return productionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRODUCTION_USER
     *
     * @param productionUser the value for conf_project_config.PRODUCTION_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProductionUser(String productionUser) {
        this.productionUser = productionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRODUCTION_TIME
     *
     * @return the value of conf_project_config.PRODUCTION_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getProductionTime() {
        return productionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRODUCTION_TIME
     *
     * @param productionTime the value for conf_project_config.PRODUCTION_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProductionTime(Date productionTime) {
        this.productionTime = productionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.TEST_VALUE
     *
     * @return the value of conf_project_config.TEST_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getTestValue() {
        return testValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.TEST_VALUE
     *
     * @param testValue the value for conf_project_config.TEST_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setTestValue(String testValue) {
        this.testValue = testValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.TEST_USER
     *
     * @return the value of conf_project_config.TEST_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getTestUser() {
        return testUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.TEST_USER
     *
     * @param testUser the value for conf_project_config.TEST_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setTestUser(String testUser) {
        this.testUser = testUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.TEST_TIME
     *
     * @return the value of conf_project_config.TEST_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.TEST_TIME
     *
     * @param testTime the value for conf_project_config.TEST_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRE_VALUE
     *
     * @return the value of conf_project_config.PRE_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getPreValue() {
        return preValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRE_VALUE
     *
     * @param preValue the value for conf_project_config.PRE_VALUE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setPreValue(String preValue) {
        this.preValue = preValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRE_USER
     *
     * @return the value of conf_project_config.PRE_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getPreUser() {
        return preUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRE_USER
     *
     * @param preUser the value for conf_project_config.PRE_USER
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setPreUser(String preUser) {
        this.preUser = preUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_config.PRE_TIME
     *
     * @return the value of conf_project_config.PRE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getPreTime() {
        return preTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_config.PRE_TIME
     *
     * @param preTime the value for conf_project_config.PRE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setPreTime(Date preTime) {
        this.preTime = preTime;
    }

    public static ConfProjectConfig loadConfigData(String configKey, String configValue, String configDesc, Long projectId, Long moduleId, String user){
        ConfProjectConfig config=new ConfProjectConfig();
        Date time=new Date();
        config.setConfigKey(configKey);
        config.setConfigValue(configValue);
        config.setConfigDesc(configDesc);
        config.setProjectId(projectId);
        config.setModuleId(moduleId);
        config.setDeleteFlag(0);
        config.setOptUser(user);
        config.setOptTime(time);
        config.setProductionValue(configValue);
        config.setProductionUser(user);
        config.setProductionTime(time);
        config.setTestValue(configValue);
        config.setTestUser(user);
        config.setTestTime(time);
        config.setPreValue(configValue);
        config.setPreUser(user);
        config.setPreTime(time);
        return config;
    }
}