package com.github.diamond.web.model;

import java.util.Date;
import java.util.List;

import com.github.diamond.web.vo.ConfRoleVo;

public class ConfUser {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long             id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.USER_CODE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String           userCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.USER_NAME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String           userName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.PASSWORD
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String           password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Integer          deleteFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.CREATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date             createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column conf_user.UPDATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date             updateTime;

    private List<ConfRoleVo> roles;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.ID
     *
     * @return the value of conf_user.ID
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.ID
     *
     * @param id the value for conf_user.ID
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.USER_CODE
     *
     * @return the value of conf_user.USER_CODE
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.USER_CODE
     *
     * @param userCode the value for conf_user.USER_CODE
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.USER_NAME
     *
     * @return the value of conf_user.USER_NAME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.USER_NAME
     *
     * @param userName the value for conf_user.USER_NAME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.PASSWORD
     *
     * @return the value of conf_user.PASSWORD
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.PASSWORD
     *
     * @param password the value for conf_user.PASSWORD
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.DELETE_FLAG
     *
     * @return the value of conf_user.DELETE_FLAG
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.DELETE_FLAG
     *
     * @param deleteFlag the value for conf_user.DELETE_FLAG
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.CREATE_TIME
     *
     * @return the value of conf_user.CREATE_TIME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.CREATE_TIME
     *
     * @param createTime the value for conf_user.CREATE_TIME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column conf_user.UPDATE_TIME
     *
     * @return the value of conf_user.UPDATE_TIME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column conf_user.UPDATE_TIME
     *
     * @param updateTime the value for conf_user.UPDATE_TIME
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<ConfRoleVo> getRoles() {
        return roles;
    }

    public void setRoles(List<ConfRoleVo> roles) {
        this.roles = roles;
    }

    @Override
    public String toString() {
        return "ConfUser{" + "id=" + id + ", userCode='" + userCode + '\'' + ", userName='" + userName + '\''
                + ", password='" + password + '\'' + ", deleteFlag=" + deleteFlag + ", createTime=" + createTime
                + ", updateTime=" + updateTime + '}';
    }

    public boolean authPwd(String md5Passwd) {
        if (md5Passwd.equals(this.getPassword())) {
            return true;
        } else {
            return false;
        }
    }
}
