package com.github.diamond.web.model;

import com.github.diamond.web.vo.ConfRoleVo;

import java.util.Date;
import java.util.List;

public class ConfProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.PROJ_CODE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String projCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.PROJ_NAME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private String projName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.OWNER_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.DEVELOPMENT_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long developmentVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.PRODUCTION_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long productionVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.PRE_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long preVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.TEST_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Long testVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.CREATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project.UPDATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    private Date updateTime;

    private String userCode;

    private List<ConfRoleVo> roles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.ID
     *
     * @return the value of conf_project.ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.ID
     *
     * @param id the value for conf_project.ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.PROJ_CODE
     *
     * @return the value of conf_project.PROJ_CODE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getProjCode() {
        return projCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.PROJ_CODE
     *
     * @param projCode the value for conf_project.PROJ_CODE
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProjCode(String projCode) {
        this.projCode = projCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.PROJ_NAME
     *
     * @return the value of conf_project.PROJ_NAME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.PROJ_NAME
     *
     * @param projName the value for conf_project.PROJ_NAME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProjName(String projName) {
        this.projName = projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.OWNER_ID
     *
     * @return the value of conf_project.OWNER_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.OWNER_ID
     *
     * @param ownerId the value for conf_project.OWNER_ID
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.DEVELOPMENT_VERSION
     *
     * @return the value of conf_project.DEVELOPMENT_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getDevelopmentVersion() {
        return developmentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.DEVELOPMENT_VERSION
     *
     * @param developmentVersion the value for conf_project.DEVELOPMENT_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setDevelopmentVersion(Long developmentVersion) {
        this.developmentVersion = developmentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.PRODUCTION_VERSION
     *
     * @return the value of conf_project.PRODUCTION_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getProductionVersion() {
        return productionVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.PRODUCTION_VERSION
     *
     * @param productionVersion the value for conf_project.PRODUCTION_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setProductionVersion(Long productionVersion) {
        this.productionVersion = productionVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.PRE_VERSION
     *
     * @return the value of conf_project.PRE_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getPreVersion() {
        return preVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.PRE_VERSION
     *
     * @param preVersion the value for conf_project.PRE_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setPreVersion(Long preVersion) {
        this.preVersion = preVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.TEST_VERSION
     *
     * @return the value of conf_project.TEST_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Long getTestVersion() {
        return testVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.TEST_VERSION
     *
     * @param testVersion the value for conf_project.TEST_VERSION
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setTestVersion(Long testVersion) {
        this.testVersion = testVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.DELETE_FLAG
     *
     * @return the value of conf_project.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.DELETE_FLAG
     *
     * @param deleteFlag the value for conf_project.DELETE_FLAG
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.CREATE_TIME
     *
     * @return the value of conf_project.CREATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.CREATE_TIME
     *
     * @param createTime the value for conf_project.CREATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project.UPDATE_TIME
     *
     * @return the value of conf_project.UPDATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project.UPDATE_TIME
     *
     * @param updateTime the value for conf_project.UPDATE_TIME
     *
     * @mbggenerated Fri May 01 20:25:16 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<ConfRoleVo> getRoles() {
        return roles;
    }

    public void setRoles(List<ConfRoleVo> roles) {
        this.roles = roles;
    }

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
}